### ISSUE TITLE
Automate submitting to Mitre

### ISSUE THREAD

**Issue by raboof** [iamamoose/Vulnogram#38]
Only available to security team, or gated by a 'reviewed by security team' flag

**Comment by iamamoose** [comment]
The code is all there, I just disabled it all during the initial roll-out.  Plan is to bring it back after thinking about that reviewed-by option and how that would reset etc

**Comment by raboof** [comment]
> how that would reset etc

I think I'd be OK with not resetting it - the chance that a project would change a CVE for the worse is fairly small, and if they do we can publish an updated CVE to Mitre easily now as part of the 'normal' handling of incoming work, without being in the critical path. The announcements would still have the bad update, but that's still better than the status quo

**Comment by iamamoose** [comment]
I've put in place the portal code and the push to cve.org button, but how this works in Vulnogram is it uses local (cached) credentials and does the push from the browser, but we're going to want projects to do it, so we'll need to convert this to a server side function instead so the users browser never sees any credentials.

**Comment by iamamoose** [comment]
this is done and live, it's restricted to security team
